In [2]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [3]:
train = pd.read_csv("../data/train.csv")
validation = pd.read_csv("../data/validation.csv")

In [6]:
features = [
    "Vol",
    "lag_15",
    "lag_30",
    "lag_60",
    "lag_120",
    "lag_1day",
    "hour",
    "day_of_week"
]

target = "target_15min"

In [7]:
X_train = train[features]
y_train = train[target]

X_val = validation[features]
y_val = validation[target]

In [8]:
X_train.head()

   Vol  lag_15  lag_30  lag_60  lag_120  lag_1day  hour  day_of_week
0  216   248.0   220.0   156.0     53.0     105.0     7            4
1  260   216.0   248.0   193.0     60.0     260.0     7            4
2  264   260.0   216.0   220.0     84.0     303.0     7            4
3   69    68.0    67.0    43.0     31.0       9.0     7            4
4  221   201.0   176.0   148.0     75.0      81.0     7            4

In [9]:
X_train.dtypes

Vol              int64
lag_15         float64
lag_30         float64
lag_60         float64
lag_120        float64
lag_1day       float64
hour             int64
day_of_week      int64
dtype: object

In [10]:
X_train.isnull().sum()

Vol            0
lag_15         0
lag_30         0
lag_60         0
lag_120        0
lag_1day       0
hour           0
day_of_week    0
dtype: int64

In [11]:
y_train.isnull().sum()

np.int64(0)

In [12]:
train[["SegmentID", "Direction"]].drop_duplicates().sort_values(
    ["SegmentID", "Direction"]
)

   SegmentID Direction
0     157501        SB
3     177615        EB
7     177615        WB
4     191114        NB

In [13]:
categorical_features = ["SegmentID", "Direction"]

numerical_features = [
    "Vol",
    "lag_15",
    "lag_30",
    "lag_60",
    "lag_120",
    "lag_1day",
    "hour",
    "day_of_week"
]

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [15]:
from sklearn.pipeline import Pipeline

linear_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", LinearRegression())
    ]
)

In [17]:
model_features = numerical_features + categorical_features

X_train = train[model_features]
X_val = validation[model_features]

y_train = train[target]
y_val = validation[target]

In [18]:
X_train.columns

Index(['Vol', 'lag_15', 'lag_30', 'lag_60', 'lag_120', 'lag_1day', 'hour',
       'day_of_week', 'SegmentID', 'Direction'],
      dtype='str')

In [19]:
linear_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['Vol', 'lag_15', 'lag_30',
                                                   'lag_60', 'lag_120',
                                                   'lag_1day', 'hour',
                                                   'day_of_week']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['SegmentID',
                                                   'Direction'])])),
                ('regressor', LinearRegression())])

In [20]:
y_val_pred = linear_model.predict(X_val)

In [21]:
val_mae = mean_absolute_error(y_val, y_val_pred)

print("Linear Regression Validation MAE:", val_mae)

Linear Regression Validation MAE: 12.44157964357832

In [22]:
val_rmse = np.sqrt(mean_squared_error(y_val, y_val_pred))

print("Linear Regression Validation RMSE:", val_rmse)

Linear Regression Validation RMSE: 17.20418200039816

In [23]:
persistence_val_pred = validation["Vol"]

persistence_val_mae = mean_absolute_error(
    y_val,
    persistence_val_pred
)

print("Persistence Validation MAE:", persistence_val_mae)

Persistence Validation MAE: 13.846625766871165

In [24]:
persistence_val_rmse = np.sqrt(
    mean_squared_error(y_val, persistence_val_pred)
)

print("Persistence Validation RMSE:", persistence_val_rmse)

Persistence Validation RMSE: 19.097318305515245

In [25]:
validation_results = pd.DataFrame({
    "Model": ["Persistence", "Linear Regression"],
    "MAE": [persistence_val_mae, val_mae],
    "RMSE": [persistence_val_rmse, val_rmse]
})

validation_results

               Model        MAE       RMSE
0        Persistence  13.846626  19.097318
1  Linear Regression  12.441580  17.204182